### PR TITLE
DUN-34

### LINKED ISSUE #33: Min Date for DateTime and Date Picker Component
**Description**
Two components need a minimum date to be specified:
* DateTime
* Date Picker

**Additional information**
From the [PM3 wiki:](https://wiki.processmaker.com/3.2/Datetime_Control)
Defines the earliest valid date that will be available in the date picker when the form is rendered.The property can be set in the control properties (using the date picker) or by using a variable to define the value @@MinDate.

**Screenshot**
image

### LINKED ISSUE #34: Max Date Property for DateTime and Date Picker Components
**Description**
Two components need a maximum date to be specified:
* DateTime
* Date Picker

**Additional information**
From the [PM3 wiki:](https://wiki.processmaker.com/3.2/Datetime_Control)
Defines the latest valid date that will be available in the date picker when the form is rendered. The property can be set in the control properties (using the date picker) or by using a variable to define the value @@MaxDate.

**Screenshot**

### PR DESCRIPTION
**Pull request by TinCodes**
Min and Max date props added with a "Clear" button.

### CODE REVIEW

File: editor/src/components/PropertiesPanel/PropertiesPanelDynamic.vue [hunk 1]
```diff
@@ -339,6 +333,20 @@ const PropertiesPanel = defineComponent({
           changedProperties: { format: data.format },
         });
       }
+      // maxDate -> to options
+      if (data.maxDate || data.maxDate == '') {
```
Comment (fagubla) [inline editor/src/components/PropertiesPanel/PropertiesPanelDynamic.vue]: Use strict equality

File: editor/src/components/PropertiesPanel/PropertiesPanelDynamic.vue [hunk 2]
```diff
@@ -339,6 +333,20 @@ const PropertiesPanel = defineComponent({
...
+        this.$store.dispatch('app/updateUISchemaElementOption', {
+          elementUUID: this.uiElement.uuid,
+          changedProperties: { maxDate: data.maxDate },
+        });
+      }
+      // minDate -> to options
+      if (data.minDate || data.minDate == '') {
```
Comment (fagubla) [inline editor/src/components/PropertiesPanel/PropertiesPanelDynamic.vue]: use strict equality

File: editor/src/components/PropertiesPanel/PropertiesPanelDynamic.vue [hunk 3]
```diff
@@ -361,7 +369,6 @@ const PropertiesPanel = defineComponent({
         });
       }
       this.generalData['data'] = data;
-      this.key++;
```
Comment (fagubla) [inline editor/src/components/PropertiesPanel/PropertiesPanelDynamic.vue:364]: Why is this line removed?

File: vue2-vuetify/src/dynaform/DateTimeControlRenderer.vue [hunk 4]
```diff
@@ -43,64 +67,222 @@ import {
...
+    VTimePicker,
+    VBtn,
     CustomControlWrapper,
   },
   props: {
     ...rendererProps<ControlElement>(),
   },
   setup(props: RendererProps<ControlElement>) {
+    let date = ref(
+      new Date(Date.now() - new Date().getTimezoneOffset() * 60000)
```
Comment (fagubla) [inline vue2-vuetify/src/dynaform/DateTimeControlRenderer.vue]: set as variable the value 60000.

File: editor/src/components/PropertiesPanel/PanelDynamic/DateProp.vue [hunk 5]
```diff
@@ -0,0 +1,97 @@
...
+      const [year, month, day] = dt.split('-');
+      return `${month}/${day}/${year}`;
+    }
+
+    function parseDate(date) {
+      if (!date) return null;
+
+      const [month, day, year] = date.split('/');
+      return `${year}-${month.padStart(2, '0')}-${day.padStart(2, '0')}`;
+    }
```
Comment (fagubla) [inline editor/src/components/PropertiesPanel/PanelDynamic/DateProp.vue]: This methods put in a composable file

File: vue2-vuetify/src/dynaform/DateTimeControlRenderer.vue [hunk 6]
```diff
@@ -43,64 +67,222 @@ import {
...
+    function formatDateTime(dt: string): string | null {
+      let [d, t] = dt.split(' ').length > 1 ? dt.split(' ') : dt.split('T');
+      if (!dt) return null;
+      return formatDate(d) + ' ' + formatTime(t);
+    }
+    // To be saved in ISO format
+    function parseDateTime(d: any, t: any): string | null {
+      if (!d || !t) return null;
+      return parseDate(d) + 'T' + formatTime(t) + ':00Z';
+    }
```
Comment (fagubla) [inline vue2-vuetify/src/dynaform/DateTimeControlRenderer.vue]: This methods put in a composable file, too

File: editor/src/components/PropertiesPanel/PanelDynamic/DateProp.vue [hunk 7]
```diff
@@ -0,0 +1,97 @@
...
+    <template v-slot:activator="{ on, attrs }">
+      <v-text-field
+        ref="text"
+        class="caption"
+        :value="formatDate(value)"
+        readonly
+        :label="config.name"
+        v-on="on"
+        v-bind="attrs"
+        @blur="date = parseDate(formatDate(value))"
```
Comment (fagubla) [inline editor/src/components/PropertiesPanel/PanelDynamic/DateProp.vue:19]: Why use blur instead of change?

File: vue2-vuetify/src/dynaform/DateTimeControlRenderer.vue [hunk 8]
```diff
@@ -8,30 +8,54 @@
...
+            :autofocus="appliedOptions.focus"
+            :placeholder="placeholder"
+            :persistent-placeholder="labelOrientation() == 'inherit'"
+            :label="labelOrientation() == 'inherit' ? computedLabel : null"
+            :persistent-hint="persistentHint()"
+            :required="control.required"
+            :error-messages="control.errors"
+            :value="valueChangeFormat"
+            @focus="isFocused = true"
+            @blur="
```
Comment (fagubla) [inline vue2-vuetify/src/dynaform/DateTimeControlRenderer.vue:33]: Why use blur instead of change?

File: vue2-vuetify/src/dynaform/DateTimeControlRenderer.vue [hunk 9]
```diff
@@ -43,64 +67,222 @@ import {
...
+      formatTime,
+      formatDateTime,
+      parseDateTime,
+      blurChangeFormat,
     };
   },
+  watch: {
+    date() {
+      this.dateFormatted = this.formatDate(this.date);
+      if (this.inputFormat == 'date-time') {
```
Comment (fagubla) [inline vue2-vuetify/src/dynaform/DateTimeControlRenderer.vue]: use strict equality

File: vue2-vuetify/src/dynaform/DateTimeControlRenderer.vue [hunk 10]
```diff
@@ -43,64 +67,222 @@ import {
...
+        this.dateTimeFormatted = this.formatDateTime(
+          this.date + ' ' + this.time
+        );
+      }
+    },
+    time() {
+      this.timeFormatted = this.formatTime(this.time);
+      if (this.inputFormat == 'date-time') {
```
Comment (fagubla) [inline vue2-vuetify/src/dynaform/DateTimeControlRenderer.vue]: use strict equality

File: vue2-vuetify/src/dynaform/DateTimeControlRenderer.vue [hunk 11]
```diff
@@ -43,64 +67,222 @@ import {
...
+    valueChangeFormat(): string | null {
+      if (this.inputFormat == 'date') {
+        return this.dateFormatted;
+      } else if (this.inputFormat == 'time') {
+        return this.timeFormatted;
+      } else if (this.inputFormat == 'date-time') {
+        return this.dateTimeFormatted;
+      } else {
+        return null;
+      }
```
Comment (fagubla) [inline vue2-vuetify/src/dynaform/DateTimeControlRenderer.vue]: strict equality

File: vue2-vuetify/src/dynaform/DateTimeControlRenderer.vue [hunk 12]
```diff
@@ -43,64 +67,222 @@ import {
...
+
+        if (current > max) {
+          min ? (min = new Date(min)) : (min = '');
+          if (!min || !(max < min)) {
+            this.date = max.toISOString().split('T')[0];
+          }
+        }
+
+        if (min) {
+          max < min ? (max = min.toISOString()) : (max = max.toISOString());
```
Comment (fagubla) [inline vue2-vuetify/src/dynaform/DateTimeControlRenderer.vue]: change for like this
`max = max < min ?  min.toISOString() : max.toISOString();`

File: vue2-vuetify/src/dynaform/DateTimeControlRenderer.vue [hunk 13]
```diff
@@ -43,64 +67,222 @@ import {
...
-      set(value: string) {
-        const datetimeLocalFormats = [
-          'YYYY-MM-DDTHH:mm:ss.SSS',
-          'YYYY-MM-DDTHH:mm:ss',
-          'YYYY-MM-DDTHH:mm',
-        ];
-        const saveFormat =
-          this.appliedOptions.dateTimeSaveFormat ?? 'YYYY-MM-DDTHH:mm:ssZ';
+        if (current < min) {
+          max ? (max = new Date(max)) : (max = '');
```
Comment (fagubla) [inline vue2-vuetify/src/dynaform/DateTimeControlRenderer.vue]: change for like this
`max = max < min ? min.toISOString() : max.toISOString();`

File: vue2-vuetify/src/dynaform/DateTimeControlRenderer.vue [hunk 14]
```diff
@@ -43,64 +67,222 @@ import {
...
+          if (!max || !(min > max)) {
+            this.date = min.toISOString().split('T')[0];
+          }
+        }
 
-        const dateTime = parseDateTime(value, datetimeLocalFormats);
-        const result = dateTime ? dateTime.format(saveFormat) : value;
+        if (max) {
+          min > max ? (min = max.toISOString()) : (min = min.toISOString());
```
Comment (fagubla) [inline vue2-vuetify/src/dynaform/DateTimeControlRenderer.vue]: change for like this
`max = max < min ? min.toISOString() : max.toISOString();`

File: vue2-vuetify/src/editor/DateTimeControlRendererEditor.vue [hunk 15]
```diff
@@ -25,7 +25,6 @@
             :placeholder="placeholder"
             :persistent-placeholder="labelOrientation() == 'inherit'"
             :label="labelOrientation() == 'inherit' ? computedLabel : null"
-            hint=""
```
Comment (fagubla) [inline vue2-vuetify/src/editor/DateTimeControlRendererEditor.vue:28]: DateTimeControl does not have hint property?

File: vue2-vuetify/src/editor/DateTimeControlRendererEditor.vue [hunk 16]
```diff
@@ -44,11 +43,12 @@
         <v-date-picker
           v-model="date"
           v-if="inputFormat == 'date' || inputFormat == 'date-time'"
```
Comment (fagubla) [inline vue2-vuetify/src/editor/DateTimeControlRendererEditor.vue]: use strict equality

File: vue2-vuetify/src/editor/DateTimeControlRendererEditor.vue [hunk 17]
```diff
@@ -135,6 +135,7 @@ const controlRenderer = defineComponent({
     function formatDate(dt: any): string | null {
       // MM-DD-YYYY format
       if (!dt) return null;
+      dt = dt.split('T')[0];
       const [year, month, day] = dt.split('-');
       return `${month}/${day}/${year}`;
     }
```
Comment (fagubla) [inline vue2-vuetify/src/editor/DateTimeControlRendererEditor.vue]: this method will be in a composable file?

File: vue2-vuetify/src/editor/DateTimeControlRendererEditor.vue [hunk 18]
```diff
@@ -152,7 +153,7 @@ const controlRenderer = defineComponent({
...
     // To be displayed to the user
     function formatDateTime(dt: string): string | null {
-      let [d, t] = dt.split(' ');
+      let [d, t] = dt.split(' ').length > 1 ? dt.split(' ') : dt.split('T');
       if (!dt) return null;
       return formatDate(d) + ' ' + formatTime(t);
     }
```
Comment (fagubla) [inline vue2-vuetify/src/editor/DateTimeControlRendererEditor.vue]: this method will be in a composable file?

File: vue2-vuetify/src/editor/DateTimeControlRendererEditor.vue [hunk 19]
```diff
@@ -237,6 +238,58 @@ const controlRenderer = defineComponent({
...
+    },
+    minDate(): string {
+      let min = this.control.uischema.options?.minDate;
+      if (min) {
+        let max = this.control.uischema.options?.maxDate;
+        let current = new Date(this.date);
+        min = new Date(min);
+
+        if (current < min) {
+          max ? (max = new Date(max)) : (max = '');
```
Comment (fagubla) [inline vue2-vuetify/src/editor/DateTimeControlRendererEditor.vue]: change for like this
`max = max < min ? min.toISOString() : max.toISOString();`

File: vue2-vuetify/src/editor/DateTimeControlRendererEditor.vue [hunk 20]
```diff
@@ -237,6 +238,58 @@ const controlRenderer = defineComponent({
...
     },
+    maxDate(): string {
+      let max = this.control.uischema.options?.maxDate;
+      if (max) {
+        let min = this.control.uischema.options?.minDate;
+        let current = new Date(this.date);
+        max = new Date(max);
+
+        if (current > max) {
+          min ? (min = new Date(min)) : (min = '');
```
Comment (fagubla) [inline vue2-vuetify/src/editor/DateTimeControlRendererEditor.vue]: change for like this
max = max < min ? min.toISOString() : max.toISOString();

File: vue2-vuetify/src/editor/DateTimeControlRendererEditor.vue [hunk 21]
```diff
@@ -237,6 +238,58 @@ const controlRenderer = defineComponent({
...
+          if (!min || !(max < min)) {
+            this.date = max.toISOString().split('T')[0];
+          }
+        }
+
+        if (min) {
+          max < min
+            ? (max = min.toISOString())
+            : (max = new Date(max).toISOString());
+          return max;
```
Comment (fagubla) [inline vue2-vuetify/src/editor/DateTimeControlRendererEditor.vue]: change for like this
`max = max < min ? min.toISOString() : max.toISOString();`

File: vue2-vuetify/src/editor/DateTimeControlRendererEditor.vue [hunk 22]
```diff
@@ -237,6 +238,58 @@ const controlRenderer = defineComponent({
...
+
+        if (current < min) {
+          max ? (max = new Date(max)) : (max = '');
+          if (!max || !(min > max)) {
+            this.date = min.toISOString().split('T')[0];
+          }
+        }
+
+        if (max) {
+          min > max
```
Comment (fagubla) [inline vue2-vuetify/src/editor/DateTimeControlRendererEditor.vue]: change for like this
max = max < min ? min.toISOString() : max.toISOString();

File: editor/src/components/PropertiesPanel/PropertiesPanelDynamic.vue (hunk 3 above)
Comment (TinCodes) [reply editor/src/components/PropertiesPanel/PropertiesPanelDynamic.vue:364]: This line was removed because it caused the sidebar to refresh 2 times and re-render the props unnecessarily. This was suggested and reviewed by @hjonathan.

File: vue2-vuetify/src/dynaform/DateTimeControlRenderer.vue (hunk 4 above)
Comment (TinCodes) [reply vue2-vuetify/src/dynaform/DateTimeControlRenderer.vue]: This is a conversion factor

File: editor/src/components/PropertiesPanel/PanelDynamic/DateProp.vue (hunk 7 above)
Comment (TinCodes) [reply editor/src/components/PropertiesPanel/PanelDynamic/DateProp.vue:19]: This textfield is read-only and the Vuetify documentation recommends using blur because of this.

File: editor/src/components/Composables/composableDateTime.ts [hunk 23]
```diff
@@ -0,0 +1,57 @@
...
+}
+
+// Returns the current Date AND Time
+export function dateTimeNow(): string {
+  return new Date(Date.now() - new Date().getTimezoneOffset() * 60000)
+    .toISOString()
+    .slice(0, 16);
+}
+
+export function formatDate(date: any): string | null {
```
Comment (fagubla) [inline editor/src/components/Composables/composableDateTime.ts:37]: Documentation missing

File: editor/src/components/Composables/composableDateTime.ts [hunk 24]
```diff
@@ -0,0 +1,57 @@
...
+  // MM-DD-YYYY format
+  if (!date) return null;
+
+  date = date.split('T')[0];
+  const [year, month, day] = date.split('-');
+  return `${month}/${day}/${year}`;
+}
+
+export function parseDate(date: any): string | null {
```
Comment (fagubla) [inline editor/src/components/Composables/composableDateTime.ts:51]: Documentation missing

File: vue2-vuetify/src/dynaform/DateTimeControlRenderer.vue [hunk 25]
```diff
@@ -43,64 +67,172 @@ import {
...
+    valueChangeFormat(): string | null {
+      if (this.inputFormat === 'date') {
+        return this.dateFormatted;
+      } else if (this.inputFormat === 'time') {
+        return this.timeFormatted;
+      } else if (this.inputFormat === 'date-time') {
+        return this.dateTimeFormatted;
+      } else {
+        return null;
+      }
```
Comment (fagubla) [inline vue2-vuetify/src/dynaform/DateTimeControlRenderer.vue]: Remove the statement else, is not necessary

File: vue2-vuetify/src/editor/DateTimeControlRendererEditor.vue [hunk 26]
```diff
@@ -77,6 +78,16 @@ import { default as ControlWrapper } from '../controls/ControlWrapper.vue';
...
+import {
+  dateNow,
+  dateTimeNow,
+  timeNow,
+  formatDate,
+  parseDate,
+  formatTime,
+  formatDateTime,
+  parseDateTime,
+} from '../../../editor/src/components/Composables/composableDateTime';
```
Comment (fagubla) [inline vue2-vuetify/src/editor/DateTimeControlRendererEditor.vue]: Please create a new composable for this package.
This is a bad practice.

File: vue2-vuetify/src/dynaform/DateTimeControlRenderer.vue (hunk 25 above)
Comment (TinCodes) [reply vue2-vuetify/src/dynaform/DateTimeControlRenderer.vue]: Removing this else statement renders the following error:
`Error: DateTimeControlRenderer.vue (180,26): semantic error TS2366: Function lacks ending return statement and return type does not include 'undefined'`

Can you suggest a fix for this please?

**Review by fagubla — APPROVED** [review]
